//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBS_Rev2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int ID { get; set; }
        public string Color { get; set; }
        public int Wheels { get; set; }
        public int LeftOrRightHand { get; set; }
        public int Seats { get; set; }
        public int BHP { get; set; }
        public Nullable<System.DateTime> ApkDate { get; set; }
        public string LicensePlate { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Catagory { get; set; }
        public string FuelType { get; set; }
        public int Mileage { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> GpsID { get; set; }
        public string Drivetrain { get; set; }
        public Nullable<System.DateTime> ManufacturingDate { get; set; }
        public Nullable<int> FleetID { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual GPSCoordinate GPSCoordinate { get; set; }
        public virtual Fleet Fleet { get; set; }
    }
}
